[project]
name = 'PredictionMarkets'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.event-betting]
path = 'contracts/event-betting.clar'
clarity_version = 2
epoch = 2.5

[contracts.market-resolution]
path = 'contracts/market-resolution.clar'
clarity_version = 2
epoch = 2.5

[contracts.oracle-integration]
path = 'contracts/oracle-integration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
